---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homepage

background:
  image: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
      #  https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

headerStyle: boxed
useEqualHeights: true

layout:
  Network:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
  Hypervisor:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
  Containers:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
  Storage:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
  Servers:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
  Home Automation:
    #useEqualHeights: true
    header: true
    style: row
    columns: 3
